### ISSUE TITLE
Не подскажите как правильно оформить теги 

### ISSUE THREAD

**Issue by Sirgalas** [corpsepk/yii2-yandex-market-yml#1]
появилась необходимость оформить следейщее 
`<param name="Размер">42-44</param><param name="Размер">0</param><param name="Размер">0</param><param name="Размер">0</param>`
и тег <keywords> не подскажите 1 как мне оформить param с атребутом и как добавить поле keyword

**Comment by corpsepk** [comment]
Есть проблема с `param`, на днях поправлю.

**Comment by corpsepk** [comment]
А разве yandex принимает тег `keywords`? Что-то я не нашел ничего о нем в хелпе...
https://yandex.ru/support/partnermarket/yml/about-yml.xml

**Comment by Sirgalas** [comment]
Я не писал что у яндекс есть тег `keywords` этот тег использует католог который во всю использует yml а вот там нужны `keywords` у Вас в модели Offer я  обнаружил следующее свойство public ```

```
$offerElementAttributes = [
        'id', 'type', 'available', 'bid', 'cbid'
    ];
```

это не то ? а если нет то очень хорошо работало свойсво `param` нельзяли при доработке была возможность добавлять свои дополнительные теги примерно как у `param`?

**Comment by corpsepk** [comment]
Поправил `param`, обновите `composer`
`composer update corpsepk/yii2-yandex-market-yml`

Атрибут `param` принимает массив:
[
    ['name' => 'Размер', 'value' => '42-44'],
    ['name' => 'Размер', 'value' => '40-44'],
]

**Comment by corpsepk** [comment]
> ...и как добавить поле keyword

Я не уверен стоит ли добавлять `keywords`, т.к. этот модуль рассчитан на yandex-market.
Как вариант можно добавить что то типа, `customAttributes` и при желании в них писать всё что угодно без валидации...

**Comment by Sirgalas** [comment]
Вы сможете это организовать в смысле customAttributes (ведь не только мне это может понадобиться)? Что бы при обновлении ваших пакетов это не слетало и мне лишний раз не наследоваться. Просто не только я такой вопрос задаю к примеру вот [на форуме](http://yiiframework.ru/forum/viewtopic.php?f=19&t=36960&p=203165#p203165) гдето в середине был вопрос

**Comment by Sirgalas** [comment]
у вас какая то ошибка вначале я дкмал что из - за того что не правильно поставил param но я его вообще закаметировал но она все равно осталась. Не формируется ни чего, что должно формироваться в моделе товара.

**Comment by corpsepk** [comment]
> у вас какая то ошибка вначале я дкмал что из - за того что не правильно поставил param но я его вообще закаметировал но она все равно осталась. Не формируется ни чего, что должно формироваться в моделе товара.

Если модель не проходит валидацию она не выводится. А ошибки пишутся в error log, посмотрите что там.

**Comment by Sirgalas** [comment]
Да всё разобрался спасибо.

**Comment by corpsepk** [comment]
> Вы сможете это организовать в смысле customAttributes (ведь не только мне это может понадобиться)?

Подумаю над этим, возможно к концу недели внесу изменения.
Этот issue закрываю.
