### ISSUE TITLE
Ошибка валидации. 

### ISSUE THREAD

**Issue by Sirgalas** [corpsepk/yii2-yandex-market-yml#3]
создал yml вашим расширением пробую пройти валидацию вот [здесь](https://webmaster.yandex.ru/tools/xml-validator/). Валидатор выдает следующую ошибку 
```
Строка: 110 Позиция: 50 
XML-файл не соответствует схеме.
Строка: 110 Позиция: 50
Подробнее
cvc-enumeration-valid: Value '1' is not facet-valid with respect to enumeration '[true, false]'. It must be a value from the enumeration.
```
и т.д. собствено вот сама эта строка 
`<offer id="13" type="vendor.model" available="1">` 
так у меня стоит приложении 
 ```
return new Offer([
                            'id' => $model->id,
                            'available' => true,...
```
Согласно [правилам](https://yandex.ru/support/partnermarket/elements/id-type-available.xml#available)  в теге должно стоять available="true"
Неоднократно мною замечено, что все теги со значением true ваше приложение выдает как 1 и валидатор воспринимает как ошибку.

**Comment by corpsepk** [comment]
Добавил в модель Offer преобразование к строке.
https://github.com/corpsepk/yii2-yandex-market-yml/blob/14957133be30f2b85e308dd31f79147b4e7f441d/models/Offer.php#L541

Попробуйте тег 0.3
https://github.com/corpsepk/yii2-yandex-market-yml/releases/tag/0.3

**Comment by Sirgalas** [comment]
Просто обновить надо ?

**Comment by corpsepk** [comment]
Ага

**Comment by Sirgalas** [comment]
Спасибо :)
