### ISSUE TITLE
Еще одна ошибка 

### ISSUE THREAD

**Issue by Sirgalas** [corpsepk/yii2-yandex-market-yml#4]
собствено вот окночание кода xml 
```
</shop>
<head/>
</yml_catalog>
```
вот на это валидатор ругается

> Недопустимое содержание было обнаружено, начиная с элемента "head".
> Строка: 8 Позиция: 8
> Подробнее
> Invalid content was found starting with element 'head'. No child element is expected at this point.

собствено вот это если руками удаляю все принимает 

`<head/>`

**Comment by corpsepk** [comment]
Сходу даже не придумать откуда он там может браться.
На всякий случай обновился у себя на проекте, тега `<head>` - нет...

**Comment by corpsepk** [comment]
Как вариант у вас какая-то собственная реализация метода Controller->renderPartial() и он внедряет тег `<head>`

**Comment by Sirgalas** [comment]
А где это может быть потому как ничего такого гне помню за собой

**Comment by corpsepk** [comment]
Хм, пришлите трейс (debug panel->logs), может это что то даст.

![image](https://cloud.githubusercontent.com/assets/2836353/23548474/bae92404-0018-11e7-9c9c-54624e6717b2.png)
