### ISSUE TITLE
Ещё вопрос но уже по категориям. 

### ISSUE THREAD

**Issue by Sirgalas** [corpsepk/yii2-yandex-market-yml#5]
У товар есть несколько категорий к примеру кофты, большие размеры, спортивные веши.
попытался реализовать в моделе товар таким образом 
```
'ymlOffer' => [
                'class' => YmlOfferBehavior::className(),
                'scope' => function ($model) {
                    /** @var \yii\db\ActiveQuery $model */
                    $model->with('category','addfeilds','prise','images');
                },
                'dataClosure' => function ($model) {
                    /** @var self $model */
                    foreach ($model->category as $category) {
                        return new Offer([
                                  ...
                                'categoryId' => $category->id,
                                  ...)]
                      }
                  }
];
выдает только товар один раз и только первой категории. Я так понимаю это гдето у Вас зашито? 
```

**Comment by corpsepk** [comment]
В справке яндекса написано:
>https://yandex.ru/support/webmaster/goods-prices/technical-requirements.xml
>`categoryId` - Идентификатор категории товара (целое число не более 18 знаков). Товарное предложение может принадлежать только одной категории.

-----

Но если отвечать на ваш вопрос, у вас цикл прерывается на первом же return...
Соответственно возвращается модель Offer с одной категорией.

То, что вы хотите сделать, я бы сделал как то так:
```php
'ymlOffer' => [
    'dataClosure' => function ($model) {
        /** @var self $model */
        $array = ArrayHelper::map($model->category, 'id', 'id');
        $string = implode(',', $array);

        return new Offer([
            ...
            'categoryId' => $string,
            ...
        )];
    }
];
```

**Comment by Sirgalas** [comment]
Я с вами насчет категорий и яндекса согласен скорее все мне прийдеся наследоваться. Но давать несколько категорий в одной  не вариант скорее получать массив и уже в представлении foreach отрабатвать получатеся

**Comment by corpsepk** [comment]
А, понятно, вы хотите чтобы было условно как с элементом `picture`.
Да, тогда вам придется форкать проект и немного менять модель Offer...

**Comment by Sirgalas** [comment]
да я так отнаследуюсь от вашей модели может и контралера от вашего. А дальше буду свое представление делать :)
