### ISSUE TITLE
Роутинг не работает

### ISSUE THREAD

**Issue by ernestby** [corpsepk/yii2-yandex-market-yml#6]
Роутинг 
['pattern'=>'market', 'route'=>'yml/default/index', 'suffix' => '.yml'],
не работает.
В чем может быть дело? Конфиги настроил.

**Comment by corpsepk** [comment]
Попробуйте пожалуйста вот так, видимо в документации ошибка.
`['pattern' => 'yandex-market', 'route' => 'yandexMarketYml/default/index', 'suffix' => '.yml'],`

**Comment by ernestby** [comment]
Спасибо за быстрый ответ.

Почему-то и так не работает.

роутинг поменял, пробую site.ru/yandex-market и site.ru/yandex-market.yml
Получаю 404.

Модели настроил, зависимости пакета доступны.

**Comment by corpsepk** [comment]
В yiisoft/yii2-debug версии 2.0.9 появилась панель "Router" со всей необходимой информацией...
Обновитесь если у вас нет этой вкладки, думаю все проблемы должны решиться.

Я попозже посмотрю, быть может сообщу что-то полезное.

**Comment by corpsepk** [comment]
Попробовал развернуть новое приложение с нуля, использовал конфиг из документации, всё работает.

Какие мне видятся варианты:
- поставить правило `['pattern' => 'yandex-market', 'route' => 'yandexMarketYml/default/index', 'suffix' => '.yml']` в начало
- посмотреть настройки вебсервера, быть может он ищет файл и не передает обработку php если не находит. В связи с чем вопрос, у вас ошибка обрабатывается yii? Или выдается ошибка вебсервера?

**Comment by ernestby** [comment]
К сожалению вкладка Router ничего мне не дало.
Ошибка обрабатывается Yii
А вот в логах идет это:
trace	yii\web\Application::handleRequest	Route requested: 'yml/default/index'

error	yii\web\HttpException:404	exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "yml/default/index".' in /home/host134/site.ru/htdocs/www/vendor/yiisoft/yii2/base/Module.php:532
Stack trace:
#0 /home/host134/site.ru/htdocs/www/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('yml/default/ind...', Array)
#1 /home/host134/site.ru/htdocs/www/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /home/host134/site.ru/htdocs/www/frontend/web/index.php(22): yii\base\Application->run()
#3 {main}

**Comment by corpsepk** [comment]
Хорошо, получается правило все таки отработало...

Поменяйте `route` на `'route' => 'YandexMarketYml/default/index'` (Yandex с большой буквы)
Поправил документацию.

**Comment by ernestby** [comment]
Спасибо за помощь! Все заработало!

**Comment by corpsepk** [comment]
Спасибо, что сообщили об ошибке!
